[package]
name = "git-commit-helper"
version = "0.1.0"
authors = ["coding@dfine.tech"]
edition = "2024"

[dependencies]
async-openai = "0.28.1"
clap = { version = "4.5.37", features = ["derive"] }
git2 = "0.20.2"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
